# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: Heroku deploy
      uses: CDNievas/heroku-action@v1.0
      with:
        # Used for authentication. You can find it in your heroku homepage account settings
        heroku_api_key: 80db25b7-362f-49e4-b305-6aa554814bfc
        # Email from Heroku Account
        heroku_email: rune.claeys@live.be
        # The appname to use for deploying/updating
        heroku_app_name: f1-predictions-frontend
     
